Distributions = Distributions or {};

local distributionTable = {

    all = {
        bin = {
            rolls = 1,
            items = {
                "Cockroach", 6,
                "Cockroach", 6,
                "Cockroach", 4,
                "Cockroach", 4,
                "DeadRat", 4,
                "DeadMouse", 2,
                "TinCanEmpty", 4,
                "TinCanEmpty", 4,
                "TinCanEmpty", 4,
                "TinCanEmpty", 4,
                "PopEmpty", 4,
                "PopEmpty", 4,
                "PopEmpty", 4,
                "PopEmpty", 4,
                "WhiskeyEmpty", 1,
                "BeerEmpty", 1,
                "WineEmpty", 1,
                "WineEmpty2", 1,
                "BandageDirty", 2,
                "BandageDirty", 2,
                "ElectronicsScrap", 2,
                "ScrapMetal", 2,
                "PopBottleEmpty", 2,
                "PopBottleEmpty", 2,
                "WaterBottleEmpty", 2,
                "WaterBottleEmpty", 2,
                "SmashedBottle", 1,
                "SmashedBottle", 1,
                "Garbagebag", 100,
            }
        },
        campfire = {
            rolls = 0,
            items = {
                
            }
        },
        cashregister = {
            rolls = 4,
            items = {
                "Money", 2,
                "Money", 100,
                "Money", 100,
            }
        },
        clothingdryer = {
            rolls = 0,
            items = {
                
            }
        },
        clothingrack = {
            procedural = true,
            procList = {
                {name="ClothingStoresDress", min=0, max=1, weightChance=100},
                {name="ClothingStoresWoman", min=0, max=10, weightChance=100},
                {name="ClothingStoresShirts", min=0, max=3, weightChance=100},
                {name="ClothingStoresPants", min=0, max=2, weightChance=100},
                {name="ClothingStoresJumpers", min=0, max=2, weightChance=100},
                {name="ClothingStoresJackets", min=0, max=1, weightChance=100},
                {name="ClothingPoor", min=0, max=99, forceForZones="Poor"},
            }
        },
        clothingwasher = {
            rolls = 0,
            items = {
                
            }
        },
        corn = {
            rolls = 2,
            items = {
                "Corn", 1,
                "Corn", 1,
                "Corn", 1,
            }
        },
        counter = {
            rolls = 1,
            items = {
                "Battery", 2,
                "Lighter", 2,
                "Torch", 2,
                "HandTorch", 3,
                "HuntingKnife", 0.5,
                "DeadRat", 0.5,
                "DeadMouse", 0.5,
                "farming.CarrotBagSeed", 1,
                "farming.BroccoliBagSeed", 1,
                "farming.RedRadishBagSeed", 1,
                "farming.StrewberrieBagSeed", 1,
                "farming.TomatoBagSeed", 1,
                "farming.PotatoBagSeed", 1,
                "farming.CabbageBagSeed", 1,
                "Pistol", 0.3,
                "Revolver_Short", 0.3,
                "DoubleBarrelShotgun", 0.5,
                "ShotgunShells", 0.6,
                "BaseballBat", 0.3,
                "Bullets9mm", 0.6,
                "Bullets38", 0.6,
                "Radio.RadioBlack",2,
                "Radio.RadioRed",1,
                "Radio.WalkieTalkie1",0.05,
                "Radio.WalkieTalkie2",0.03,
                "Radio.WalkieTalkie3",0.001,
            },
            junk = {
                rolls = 1,
                items = {
                    "Pen", 4,
                    "BluePen", 2,
                    "RedPen", 2,
                    "Pencil", 4,
                    "RubberBand", 2,
                    "Tissue", 4,
                    "Candle", 4,
                    "Matches", 4,
                    "Mugl", 2,
                    "MugRed", 2,
                    "MugWhite", 3,
                    "EmptyJar", 1,
                    "JarLid", 1,
                    "Vinegar", 1,
                }
            }
        },
        crate = {
            rolls = 1,
            items = {
                "NailsBox", 1,
                "PaperclipBox", 0.5,
                "DuctTape", 0.8,
                "Glue", 0.8,
                "Scotchtape", 0.8,
                "Twine", 0.8,
                "Thread", 1.5,
                "Needle", 0.8,
                "Woodglue", 0.8,
                "Rope", 0.8,
                "NailsBox", 4,
                "NailsBox", 4,
                "NailsBox", 4,
                "Hammer", 4,
                "Wire", 2,
                "Crowbar", 1,
                "Tarp", 1,
                "Saw", 1,
                "GardenSaw", 1,
                "Plank", 3,
                "Plank", 3,
                "Battery", 4,
                "Lighter", 4,
                "camping.TentPeg", 7,
                "Sledgehammer", 0.4,
                "Sledgehammer2", 0.4,
                "Paperclip", 0.8,
                "Axe", 0.4,
                "WoodAxe", 0.4,
                "farming.CarrotBagSeed", 1.5,
                "farming.BroccoliBagSeed", 1.5,
                "farming.RedRadishBagSeed", 1.5,
                "farming.StrewberrieBagSeed", 1.5,
                "farming.TomatoBagSeed", 1.5,
                "farming.PotatoBagSeed", 1.5,
                "farming.CabbageBagSeed", 1.5,
                "farming.HandShovel", 2.7,
                "HandScythe", 0.5,
                "HandFork", 0.5,
                "Shovel", 0.5,
                "Shovel2", 0.5,
                "SnowShovel", 0.5,
                "farming.WateredCan", 1,
                "Paintbrush", 1.5,
                "PaintBlue", 0.8,
                "PaintBlack", 0.8,
                "PaintRed", 0.8,
                "PaintBrown", 0.8,
                "PaintCyan", 0.8,
                "PaintGreen", 0.8,
                "PaintGrey", 0.8,
                "PaintLightBlue", 0.8,
                "PaintLightBrown", 0.8,
                "PaintOrange", 0.8,
                "PaintPink", 0.8,
                "PaintPurple", 0.8,
                "PaintTurquoise",0.8,
                "PaintWhite", 0.8,
                "PaintYellow", 0.8,
                "PlasterPowder", 2,
                "ConcretePowder", 1,
                "BucketEmpty", 2,
                "Shotgun", 0.5,
                "DoubleBarrelShotgun", 0.2,
                "ShotgunShells", 1,
                "ShotgunShells", 1,
                "ShotgunShells", 1,
                "ShotgunShells", 0.5,
                "ShotgunShells", 0.5,
                "Torch", 1,
                "HandTorch", 1,
                "BarbedWire", 1,
                "Sandbag", 0.5,
                "Gravelbag", 0.5,
                "EmptySandbag", 2.5,
                "Fertilizer", 0.5,
                "Charcoal", 6,
                --                "BallPeenHammer", 0.01,
                --                "Tongs", 0.01,
                "Radio.WalkieTalkie1",0.05,
                "Radio.WalkieTalkie2",0.03,
                "Radio.WalkieTalkie3",0.001,
                "Radio.HamRadio1",0.005,
                "BlowTorch", 0.8,
                "WeldingRods", 2,
                "SheetMetal", 2,
                "SmallSheetMetal", 2.4,
                "MetalPipe", 2,
                "MetalBar", 1.2,
                "WeldingMask",0.7,
                "Wrench", 0.5,
                "LugWrench",0.4,
                "Jack", 0.2,
                "TirePump", 0.2,
                "LeadPipe", 0.4,
                "HandAxe", 0.2,
                "PipeWrench", 0.4,
                "Plunger", 0.5,
                "ClubHammer", 0.3,
                "WoodenMallet", 0.3,
            }
        },
        desk = {
            procedural = true,
            procList = {
                {name="DeskGeneric", min=0, max=99},
            }
        },
        dishescabinet = {
            rolls = 6,
            items = {
                "DO7BE_COOKIE.Do7beCookie", 100,
                "BreadKnife", 5,
                "Spoon", 10,
                "Fork", 10,
                "Bowl", 10,
            }
        },
        displaycasebakery = {
            procedural = true,
            procList = {
                {name="BakeryBread", min=0, max=99, weightChance=100},
                {name="BakeryPie", min=0, max=99, weightChance=60},
                {name="BakeryCake", min=0, max=99, weightChance=80},
                {name="BakeryMisc", min=0, max=99, weightChance=20},
            }
        },
        dresser = { 
            procedural = true,
            procList = {
                {name="DresserGeneric", min=0, max=99},
            }
        },
        filingcabinet = {
            rolls = 1,
            items = {
                "Magazine", 4,
                "Newspaper", 4,
                "Book", 4,
                "ComicBook", 2,
            },
            junk = {
                rolls = 1,
                items = {
                    "SheetPaper2", 20,
                    "SheetPaper2", 20,
                    "SheetPaper2", 20,
                    "SheetPaper2", 20,
                    "Notebook", 4,
                }
            }
        },
        freezer = {
            rolls = 3,
            items = {
                "Icecream", 3,
                "Icecream", 3,
                "Icecream", 3,
                "Pizza", 1,
                "BurgerRecipe", 1,
                "Peas", 3,
                "Pie", 1,
                "Steak", 1,
                "Chicken", 1,
                "Salmon", 1,
                "Coldpack",2,
                "Coldpack",2,
                "PorkChop", 1,
                "MuttonChop", 1,
                "IcePick", 0.2,
            }
        },
        fridge = {
            rolls = 1,
            items = {
                "DO7BE_COOKIE.Do7beCookie", 100,
                "Milk", 8,
                "Milk", 4,
                "BeefJerky", 3,
                "Bread", 4,
                "Carrots", 4,
                "Steak", 3,
                "MeatPatty", 3,
                "Chicken", 3,
                "Ham", 3,
                "Salmon", 3,
                "Cheese", 4,
                "Watermelon", 4,
                "Broccoli", 4,
                "Pie", 3,
                "PopBottle", 3,
                "PopBottle", 3,
                "Butter", 3,
                "EggCarton", 4,
                "EggCarton", 2,
                "Apple", 4,
                "Orange", 4,
                "Banana", 4,
                "farming.RedRadish", 4,
                "farming.Strewberrie", 4,
                "Cherry", 4,
                "farming.Tomato", 4,
                "farming.Cabbage", 4,
                "Lettuce", 3,
                "Pickles", 3,
                "BellPepper", 3,
                "Peach", 3,
                "CakeSlice", 3,
                "Mustard", 2,
                "Ketchup", 2,
                "Processedcheese", 5,
                "Corndog", 2,
                "PorkChop", 3,
                "MuttonChop", 3,
                "Onion", 3,
                "Lemon", 3,
                "WaterBottleFull", 3,
                "WaterBottleFull", 3,
                "WaterBottleFull", 3,
                "Wine", 2,
                "Corn", 4,
                "Eggplant", 4,
                "Leek", 4,
                "Grapes", 4,
                "farming.Bacon", 4,
                "farming.MayonnaiseFull", 2,
                "farming.RemouladeFull", 0.5,
                "Worm", 0.3,
                "Avocado", 3,
                "Pineapple", 3,
                "Zucchini", 3,
                "Tofu", 2,
                "Yoghurt", 3,
                "JuiceBox", 1,
                "BeerCan", 1,
                "BeerCan", 1,
                "BeerCan", 1,
                "BeerBottle", 1,
            }
        },
        fruitbusha = {
            rolls = 10,
            items = {
                "BerryBlack", 50,
            },
            noAutoAge = true,
        },
        fruitbushb = {
            rolls = 10,
            items = {
                "BerryBlue", 50,
            },
            noAutoAge = true,
        },
        fruitbushc = {
            rolls = 10,
            items = {
                "BerryGeneric1", 50,
            },
            noAutoAge = true,
        },
        fruitbushd = {
            rolls = 10,
            items = {
                "BerryGeneric2", 25,
                "BerryGeneric5", 25,
            },
            noAutoAge = true,
        },
        fruitbushe = {
            rolls = 10,
            items = {
                "BerryGeneric3", 25,
                "BerryGeneric4", 25,
            },
            noAutoAge = true,
        },
        inventoryfemale = {
            rolls = 1,
            items = {
                "DO7BE_COOKIE.Do7beCookie", 100,
                "MuldraughMap", 0.2,
                "WestpointMap", 0.2,
                "MarchRidgeMap",0.1,
                "RosewoodMap",0.1,
                "RiversideMap",0.1,
                "Lipstick", 1,
                "MakeupEyeshadow", 1,
                "MakeupFoundation", 1,
                "Earbuds", 1,
                "Locket", 1,
                "Comb", 1,
                "Magazine", 1,
                "Newspaper", 1,
                "Notebook", 1,
                "Pencil", 1,
                "Pen", 1,
                "BluePen", 1,
                "RedPen", 1,
                "Doll", 0.5,
                "Pills", 0.1,
                "PillsBeta", 0.1,
                "PillsAntiDep", 0.1,
                "PillsVitamins", 0.1,
                "Pistol", 0.05,
                "Pistol2", 0.02,
                "Revolver_Short", 0.05,
                "CreditCard", 1,
                "Perfume", 0.5,
                "Radio.WalkieTalkie1",0.05,
                "Radio.WalkieTalkie2",0.03,
                "Radio.WalkieTalkie3",0.001,
                "Cigarettes", 0.5,
                "Matches", 0.4,
                "Lighter", 0.4,
            }
        },
        inventorymale = {
            rolls = 1,
            items = {
                "DO7BE_COOKIE.Do7beCookie", 100,
                "MuldraughMap", 0.2,
                "WestpointMap", 0.2,
                "MarchRidgeMap",0.1,
                "RosewoodMap",0.1,
                "RiversideMap",0.1,
                "Wallet", 1,
                "Wallet2", 1,
                "Wallet3", 1,
                "Wallet4", 1,
                "Locket", 1,
                "Comb", 1,
                "Magazine", 1,
                "Newspaper", 1,
                "Notebook", 1,
                "Pencil", 1,
                "Pen", 0.1,
                "BluePen", 0.1,
                "RedPen", 0.1,
                "Pills", 0.1,
                "PillsBeta", 0.1,
                "PillsAntiDep", 0.1,
                "PillsVitamins", 0.1,
                "Pistol", 0.05,
                "Pistol2", 0.02,
                "Revolver_Short", 0.05,
                "Cologne", 0.2,
                "CreditCard", 1,
                "Radio.WalkieTalkie1",0.05,
                "Radio.WalkieTalkie2",0.03,
                "Radio.WalkieTalkie3",0.001,
                "Cigarettes", 0.5,
                "Matches", 0.4,
                "Lighter", 0.4,
            }
        },
        locker = {
            procedural = true,
            procList = {
                {name="Locker", min=0, max=99, weightChance=100},
                {name="LockerClassy", min=0, max=99, forceForZones="Rich"},
            }
        },
        logs = {
            rolls = 1,
            items = {
                "Log", 100,
                "Log", 100,
                "Log", 7,
                "Log", 7,
                "Log", 7,
                "Log", 7,
                "Log", 7,
            }
        },
        medicine = {
            rolls = 3,
            items = {
                "Bandaid", 7,
                "Pills", 7,
                "PillsBeta", 7,
                "PillsAntiDep", 7,
                "PillsSleepingTablets", 7,
                "PillsVitamins", 7,
                "Tweezers", 5,
                "Antibiotics", 5,
            }
        },
        metal_shelves = {
            rolls = 3,
            items = {
                "NailsBox", 1,
                "PaperclipBox", 0.8,
                "DuctTape", 0.8,
                "Glue", 0.8,
                "Scotchtape", 0.8,
                "Twine", 0.8,
                "Thread", 1.5,
                "Needle", 0.8,
                "Woodglue", 0.8,
                "Rope", 0.8,
                "Nails", 3,
                "Nails", 3,
                "Poolcue", 2,
                "Hammer", 3,
                "Wire", 1.5,
                "Saw", 1,
                "GardenSaw", 1,
                "Torch", 2,
                "HandTorch", 3,
                "Battery", 3,
                "Screwdriver", 1,
                "Toolbox", 0.5,
                "Radio.ElectricWire", 2,
                "Golfclub", 2,
                "Crowbar", 2,
                "Paperclip", 2,
                "Radio.RadioBlack",2,
                "Radio.RadioRed",1,
                "Radio.WalkieTalkie1",0.05,
                "Radio.WalkieTalkie2",0.03,
                "Radio.WalkieTalkie3",0.01,
                "Radio.WalkieTalkie4",0.005,
                "Radio.WalkieTalkie5",0.001,
                "LeadPipe", 1,
                "HandAxe", 0.8,
                "PipeWrench", 1,
                "ClubHammer", 1,
                "WoodenMallet", 1,
            }
        },
        microwave = {
            rolls = 0,
            items = {
            }
        },
        officedrawers = {
            rolls = 1,
            items = {
                "Battery", 3,
                "Nails", 3,
                "Nails", 3,
                "Nails", 2,
                "Lighter", 3,
                "Torch", 1,
                "HandTorch", 3,
                "WhiskeyFull", 2,
                "Chocolate", 3,
                "Pills", 1,
                "PillsBeta", 1,
                "PillsAntiDep", 1,
                "PillsSleepingTablets", 1,
                "Crisps", 2,
                "Crisps2", 2,
                "Crisps3", 2,
                "Pop", 2,
                "Pop2", 2,
                "Pop3", 2,
                "Magazine", 3,
                "Newspaper", 3,
                "Book", 3,
                "ComicBook", 1,
                "Lollipop", 2,
                "MintCandy", 2,
                "SheetPaper2", 3,
                "Matches", 2,
                "PillsVitamins", 1,
                "Magazine", 2,
                "Newspaper", 2,
                "Book", 2,
                "Cigarettes", 1,
                "Radio.RadioBlack",2,
                "Radio.RadioRed",1,
                "LetterOpener",1,
            },
            junk = {
                rolls = 1,
                items = {
                    "SheetPaper2", 2,
                    "Notebook", 2,
                    "Pencil", 3,
                    "Pen", 3,
                    "BluePen", 1,
                    "RedPen", 1,
                    "Scissors", 3,
                    "Cologne", 1,
                    "Perfume", 1,
                    "CardDeck", 1,
                    "Comb", 2,
                    "Toothbrush", 1,
                    "Notebook", 3,
                    "Razor", 1,
                    "Lipstick", 1,
                    "MakeupEyeshadow", 1,
                    "MakeupFoundation", 1,
                    "Pen", 4,
                    "BluePen", 2,
                    "RedPen", 2,
                    "Pencil", 4,
                    "RubberBand", 4,
                    "Eraser", 4,
                    "Paperclip", 4,
                    "Paperclip", 4,
                    "Tissue", 3,
                }
            }
        },
        other = {
            procedural = true,
            procList = {
                {name="OtherGeneric", min=0, max=99},
            }
        },
        plankstash = {
            procedural = true,
            procList = {
                {name="PlankStashMoney", min=0, max=1, weightChance=100},
                {name="PlankStashWeapon", min=0, max=1, weightChance=100},
            }
        },
        postbox = {
            rolls = 3,
            items = {
                "Newspaper", 2,
                "Magazine", 2,
                "FishingMag1", 0.2,
                "FishingMag2", 0.2,
                "HuntingMag1", 0.2,
                "HuntingMag2", 0.2,
                "HuntingMag3", 0.2,
                "HerbalistMag", 0.2,
                "CookingMag1", 0.2,
                "CookingMag2", 0.2,
                "ElectronicsMag1", 0.2,
                "ElectronicsMag2", 0.2,
                "ElectronicsMag3", 0.2,
                "ElectronicsMag4", 0.2,
                "ElectronicsMag5", 0.2,
                "MechanicMag1", 0.2,
                "MechanicMag2", 0.2,
                "MechanicMag3", 0.2,
                "EngineerMagazine1", 0.2,
                "EngineerMagazine2", 0.2,
                "MetalworkMag1", 0.2,
                "MetalworkMag2", 0.2,
                "MetalworkMag3", 0.2,
                "MetalworkMag4", 0.2,
            }
        },
        restaurantdisplay = {
            procedural = true,
            procList = {
                {name="ServingTrayBurgers", min=0, max=99, weightChance=100},
                {name="ServingTrayChicken", min=0, max=99, weightChance=100},
                {name="ServingTrayFries", min=0, max=99, weightChance=100},
                {name="ServingTrayHotdogs", min=0, max=99, weightChance=100},
                {name="ServingTrayPie", min=0, max=99, weightChance=100},
                {name="ServingTrayPizza", min=0, max=99, weightChance=100},
            }
        },
        shelves = {
            procedural = true,
            procList = {
                {name="ShelfGeneric", min=0, max=99},
            }
        },
        shelvesmag = {
            procedural = true,
            procList = {
                {name="MagazineRackMaps", min=0, max=1, weightChance=50},
                {name="MagazineRackNewspaper", min=0, max=1, weightChance=50},
                {name="MagazineRackMixed", min=0, max=99, weightChance=100},
            }
        },
        sidetable = {
            rolls = 1,
            items = {
                "Battery", 2,
                "Lighter", 2,
                "Torch", 1,
                "HandTorch", 1.5,
                "Journal", 2,
                "Magazine", 4,
                "Newspaper", 4,
                "Book", 4,
                "ComicBook", 2,
                "Cigarettes", 4,
                "BookCarpentry1", 1,
                --                "BookBlacksmith1", 1,
                "BookFirstAid1", 1,
                "BookMetalWelding1", 1,
                "BookMetalWelding1", 1,
                "BookElectrician1", 1,
                "BookMechanic1" , 1,
                "BookFarming1", 1,
                "BookForaging1", 1,
                "BookCooking1", 1,
                "BookFishing1", 1,
                "BookTrapping1", 1,
                "BookCarpentry2", 0.5,
                "BookFarming2", 0.5,
                "BookForaging2", 0.5,
                "BookCooking2", 0.5,
                "BookFishing2", 0.5,
                "BookTrapping2", 0.5,
                --                "BookBlacksmith2", 0.5,
                "BookFirstAid2", 0.5,
                "BookMetalWelding2", 0.5,
                "BookElectrician2", 0.5,
                "BookMechanic2", 0.5,
                "Key1", 1,
                "Key2", 1,
                "Key3", 1,
                "Key4", 1,
                "Key5", 1,
                "HomeAlarm", 1,
                "Radio.RadioBlack",2,
                "Radio.RadioRed",1,
                "Radio.WalkieTalkie1",0.05,
                "Radio.WalkieTalkie2",0.03,
                "Radio.WalkieTalkie3",0.001,
                "Remote", 8,
                "MuldraughMap", 0.05,
                "WestpointMap", 0.05,
                "MarchRidgeMap",0.01,
                "RosewoodMap",0.01,
                "RiversideMap",0.01,
                "FishingMag1", 0.7,
                "FishingMag2", 0.7,
                "HuntingMag1", 0.7,
                "HuntingMag2", 0.7,
                "HuntingMag3", 0.7,
                "HerbalistMag", 0.7,
                "CookingMag1", 0.7,
                "CookingMag2", 0.7,
                "ElectronicsMag1", 0.7,
                "ElectronicsMag2", 0.7,
                "ElectronicsMag3", 0.7,
                "ElectronicsMag4", 0.7,
                "ElectronicsMag5", 0.7,
                "MechanicMag1", 0.7,
                "MechanicMag2", 0.7,
                "MechanicMag3", 0.7,
                "EngineerMagazine1", 0.7,
                "EngineerMagazine2", 0.7,
                "MetalworkMag1", 0.7,
                "MetalworkMag2", 0.7,
                "MetalworkMag3", 0.7,
                "MetalworkMag4", 0.7,
            },
            junk = {
                rolls = 1,
                items = {
                    "Pen", 4,
                    "BluePen", 2,
                    "RedPen", 2,
                    "Paperclip", 1,
                    "Pencil", 4,
                    "RubberBand", 2,
                    "Eraser", 4,
                    "Tissue", 9,
                    "Candle", 4,
                    "Matches", 3,
                    "SheetPaper2", 4,
                    "Notebook", 4,
                }
            }
        },
        stove = {
            rolls = 0,
            items = {
            }
        },
        vendingpop = {
            rolls = 4,
            items = {
                "Pop", 4,
                "Pop2", 4,
                "Pop3", 4,
                "PopBottle", 3,
                "Pop", 4,
                "Pop2", 4,
                "Pop3", 4,
                "PopBottle", 3,
                "Pop", 4,
                "Pop2", 4,
                "Pop3", 4,
                "PopBottle", 3,
            }
        },
        vendingsnack = {
            rolls = 4,
            items = {
                "Crisps", 4,
                "Crisps2", 4,
                "Crisps3", 4,
                "Crisps", 4,
                "Crisps2", 4,
                "Crisps3", 4,
                "Crisps", 4,
                "Crisps2", 4,
                "Crisps3", 4,
            }
        },
        wardrobe = {
            procedural = true,
            procList = {
                {name="WardrobeMan", min=0, max=2, weightChance=100},
                {name="WardrobeManClassy", min=0, max=1, weightChance=100},
                {name="WardrobeWoman", min=0, max=2, weightChance=100},
            }
        },
        
        -- This is an example to add a specific distribution on a dead corpse according to his outfit
        Outfit_Generic99 = {
            rolls = 100,
            items = {
                "Wallet", 100,
            }
        },
    },
}

table.insert(Distributions, 1, distributionTable);

--for mod compat:
SuburbsDistributions = distributionTable;
